#ifndef GRAPHVEX_TYPE_H
#define GRAPHVEX_TYPE_H

#include "oop/type.h"

// graphvex/type.h — the graphvex project's type registry.
//
// OWNERSHIP: every graphvex class ID lives here, not in vexspoke's
// oop/type.h. Included by graphvex sources that stamp headers with
// graphvex-owned types (font atlases today; texture/vfs classes next).
//
// CLASS-SPACE CONTRACT (Rule 17): graphvex classes live in 0x0100-0x01FF.
// All new graphvex IDs MUST land in that range — the central parent chain
// and arch switch in vexspoke oop/type.c dispatch on ranges and may not
// include this file (upstream builds standalone).

// --- GRAPHVEX GPU OBJECTS ---
#define ID_FONT	0x0100u
#define ID_IMAGE	0x0101u
#define ID_SWAPCHAIN	0x0102u
#define ID_SEMAPHORE	0x0103u
#define ID_FENCE	0x0104u
#define ID_COMMAND_BUFFER	0x0105u
#define ID_COMMAND_QUEUE	0x0106u
#define ID_GPU_BUFFER	0x0107u
#define ID_BINDLESS_HEAP	0x0108u
#define ID_SHAPE	0x0109u
#define ID_MESH	0x010Au
#define ID_MESHLET	0x010Bu
#define ID_SCENE	0x010Cu
#define ID_STROKE	0x010Du
#define ID_BRUSH	0x010Eu
#define ID_VECTOR_BRUSH	0x010Fu
#define ID_RASTER_BRUSH	0x0110u
#define ID_DRAWABLE	0x0111u
#define ID_LAYERED_DRAWABLE	0x0112u
#define ID_VECTOR_DRAWABLE	0x0113u
#define ID_LAYERED_VECTOR_DRAWABLE	0x0114u
#define ID_PIPELINE	0x0115u
#define ID_PASS	0x0116u
/* 0x0117-0x0118 reserved — next free ID is 0x0117u. */

#define TYPE_FONT_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_FONT)
#define TYPE_IMAGE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_IMAGE)
#define TYPE_SWAPCHAIN_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SWAPCHAIN)
#define TYPE_SEMAPHORE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SEMAPHORE)
#define TYPE_FENCE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_FENCE)
#define TYPE_COMMAND_BUFFER_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_COMMAND_BUFFER)
#define TYPE_COMMAND_QUEUE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_COMMAND_QUEUE)
#define TYPE_GPU_BUFFER_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_GPU_BUFFER)
#define TYPE_BINDLESS_HEAP_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_BINDLESS_HEAP)
#define TYPE_SHAPE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SHAPE)
#define TYPE_MESH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_MESH)
#define TYPE_MESHLET_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_MESHLET)
#define TYPE_SCENE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_SCENE)
#define TYPE_STROKE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_STROKE)
#define TYPE_BRUSH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_BRUSH)
#define TYPE_VECTOR_BRUSH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_VECTOR_BRUSH)
#define TYPE_RASTER_BRUSH_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_RASTER_BRUSH)
#define TYPE_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_DRAWABLE)
#define TYPE_LAYERED_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_LAYERED_DRAWABLE)
#define TYPE_VECTOR_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_VECTOR_DRAWABLE)
#define TYPE_LAYERED_VECTOR_DRAWABLE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_LAYERED_VECTOR_DRAWABLE)
#define TYPE_PIPELINE_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_PIPELINE)
#define TYPE_PASS_SINGLETON	(PROJ_GRAPHVEX | FORM_SINGLETON | ID_PASS)

#endif
